# Generated by Django 6.0.2 on 2026-05-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.FloatField()),
                ('worked_days', models.IntegerField()),
                ('lop_days', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('deductions', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('status', models.CharField(choices=[('Calculated', 'Calculated'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Calculated', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'employee_name'],
                'unique_together': {('tenant_id', 'employee_id', 'month', 'year')},
            },
        ),
    ]
